services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=adymnar
    ports:
      - 5432:5432
    networks:
      - my-net
  app:
    image: app:latest
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - my-net
networks:
  my-net:
    driver: bridge